repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: ^\.idea
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-yaml
  - id: check-toml
  - id: check-xml
  - id: check-added-large-files
  - id: forbid-submodules
  - id: mixed-line-ending
- repo: https://github.com/google/yamlfmt
  rev: v0.17.2
  hooks:
  - id: yamlfmt
- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
  - id: actionlint
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 3.4.0
  hooks:
  - id: editorconfig-checker
    exclude: LICENSE|^\.idea
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.34.0
  hooks:
  - id: check-github-workflows
  - id: check-renovate
- repo: https://github.com/renovatebot/pre-commit-hooks
  rev: 41.116.6
  hooks:
  - id: renovate-config-validator
    args: [--strict]
- repo: https://github.com/andrewaylett/pre-commit-hooks
  rev: v0.7.0
  hooks:
  - id: init-hooks
