name: pre-commit
description: run pre-commit
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
  pre_commit_version:
    description: the version of pre-commit to use
    required: false
    default: '4.1.0'
runs:
  using: composite
  steps:
  - uses: astral-sh/setup-uv@445689ea25e0de0a23313031f5fe577c74ae45a1 # v6
    with:
      enable-cache: false
  - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
    with:
      path: ~/.cache/pre-commit
      key: pre-commit-${ inputs.pre_commit_version }|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
  - run: uvx --isolated --with 'pre-commit==${{ inputs.pre_commit_version }}' --cache-dir '~/.cache/pre-commit/uv' pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
    shell: bash
