name: Cached Pre-Commit
description: Validates that your commit passes all its pre-commit rules, with caching from uv.
author: Andrew Aylett
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
  pre_commit_version:
    description: the version of pre-commit to use
    required: false
    default: '4.5.1'
  pre_commit_uv_version:
    description: the version of pre-commit-uv to use
    required: false
    default: '4.2.0'
  uv_version:
    description: the version of uv to use
    required: false
    default: '0.9.29'
runs:
  using: composite
  steps:
  - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
    with:
      path: ~/.cache/pre-commit
      key: andrewaylett/pre-commit-action/${{ hashFiles('.pre-commit-config.yaml') }}/${{ github.action_ref }}
      restore-keys: |
        andrewaylett/pre-commit-action/${{ hashFiles('.pre-commit-config.yaml') }}/
        andrewaylett/pre-commit-action/
  - uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41 # v7.2.1
    id: uv
    with:
      enable-cache: false
      cache-local-path: ~/.cache/pre-commit/uv
      version: ${{ inputs.uv_version }}
  - run: |
      # Set up and execute pre-commit
      set -eu
      echo ::group::Ensure pre-commit environment
      ${{ steps.uv.outputs.uv-path }} tool install 'pre-commit==${{ inputs.pre_commit_version }}' --with 'pre-commit-uv==${{ inputs.pre_commit_uv_version }}' --cache-dir '~/.cache/pre-commit/uv'
      echo ::endgroup::
      ${{ steps.uv.outputs.uv-path }} tool run --from 'pre-commit==${{ inputs.pre_commit_version }}' --with 'pre-commit-uv==${{ inputs.pre_commit_uv_version }}' --cache-dir '~/.cache/pre-commit/uv' pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
      echo ::group::Clean pre-commit cache
      ${{ steps.uv.outputs.uv-path }} tool run --from 'pre-commit==${{ inputs.pre_commit_version }}' --with 'pre-commit-uv==${{ inputs.pre_commit_uv_version }}' --cache-dir '~/.cache/pre-commit/uv' pre-commit gc
      echo ::endgroup::
      echo ::group::Clean uv cache
      ${{ steps.uv.outputs.uv-path }} cache prune --ci
      echo ::endgroup::
    shell: bash
branding:
  icon: check-circle
  color: blue
