name: Cached Pre-Commit
description: Validates that your commit passes all its pre-commit rules, with caching from uv.
author: Andrew Aylett
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
  pre_commit_version:
    description: the version of pre-commit to use
    required: false
    default: '4.2.0'
  pre_commit_uv_version:
    description: the version of pre-commit-uv to use
    required: false
    default: '4.1.4'
  uv_version:
    description: the version of uv to use
    required: false
    default: '0.8.8'
runs:
  using: composite
  steps:
  - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
    with:
      path: ~/.cache/pre-commit
      key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}|${{ github.action_ref }}|
      restore-keys: |
        pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}|
        pre-commit-
  - uses: astral-sh/setup-uv@e92bafb6253dcd438e0484186d7669ea7a8ca1cc # v6.4.3
    id: uv
    with:
      enable-cache: false
      cache-local-path: ~/.cache/pre-commit/uv
      version: ${{ inputs.uv_version }}
  - run: |
      set -eu
      echo ::group::Ensure pre-commit environment
      ${{ steps.uv.outputs.uv-path }} tool install 'pre-commit==${{ inputs.pre_commit_version }}' --with 'pre-commit-uv==${{ inputs.pre_commit_uv_version }}' --cache-dir '~/.cache/pre-commit/uv'
      echo ::endgroup::
      ${{ steps.uv.outputs.uv-path }} tool run --offline --from 'pre-commit==${{ inputs.pre_commit_version }}' --with 'pre-commit-uv==${{ inputs.pre_commit_uv_version }}' --cache-dir '~/.cache/pre-commit/uv' pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
      echo ::group::Clean pre-commit cache
      ${{ steps.uv.outputs.uv-path }} tool run --offline --from 'pre-commit==${{ inputs.pre_commit_version }}' --cache-dir '~/.cache/pre-commit/uv' pre-commit gc
      echo ::endgroup::
      echo ::group::Clean uv cache
      ${{ steps.uv.outputs.uv-path }}  cache prune --ci
      echo ::endgroup::
    shell: bash
branding:
  icon: check-circle
  color: blue
