name: Run Pre-Commit
description: Validates that your commit passes all its pre-commit rules
author: Andrew Aylett
inputs:
  extra_args:
    description: options to pass to pre-commit run
    required: false
    default: '--all-files'
  pre_commit_version:
    description: the version of pre-commit to use
    required: false
    default: '4.2.0'
  uv_version:
    description: the version of uv to use
    required: false
    default: '0.7.15'
runs:
  using: composite
  steps:
  - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
    with:
      path: ~/.cache/pre-commit
      key: pre-commit-${{ inputs.pre_commit_version }}|${{ inputs.uv_version }}|${{ hashFiles('.pre-commit-config.yaml') }}
      restore-keys: |
        pre-commit-${{ inputs.pre_commit_version }}|${{ inputs.uv_version }}|
        pre-commit-${{ inputs.pre_commit_version }}|
        pre-commit-
  - uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba # v6
    with:
      enable-cache: false
      cache-local-path: ~/.cache/pre-commit/uv
      version: ${{ inputs.uv_version }}
  - run: |
      set -eu
      uvx --isolated --with 'pre-commit==${{ inputs.pre_commit_version }}' --cache-dir '~/.cache/pre-commit/uv' pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
      uv cache prune --ci
    shell: bash
branding:
  icon: check-circle
  color: blue
